# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'capybara/rspec'
require 'bundler'
Bundler.require(:default)
# require_all 'spec/lib'

url = 'http://localhost:4444//wd/hub'

capabilities = Selenium::WebDriver::Remote::Capabilities.chrome

Capybara.register_driver :remote_browser do |app|
  Capybara::Selenium::Driver.new(
      app,
      :browser => :remote,
      url: url,
      desired_capabilities: capabilities
  )
end

Capybara.default_driver = :remote_browser
Capybara.javascript_driver = :remote_browser